dependencyResolutionManagement {
    repositories {
        exclusiveContent {
            forRepository {
                mavenLocal()
            }
            filter {
                includeGroup('org.example')
            }
        }
        mavenCentral()
    }
}

rootProject.name = 'outer'
include('core')
